version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  ia-service:
    build: ./ia-service
    container_name: ia-service
    ports:
      - '5000:5000'
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '4000:4000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/adaptiveDB
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
      - ia-service
volumes:
  mongo-data: